# Generated by Django 5.2.11 on 2026-02-15 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Owner (Super Admin)'), ('head_manager', 'Head Manager'), ('manager', 'Manager'), ('teacher', 'Teacher (Ustad)'), ('student', 'Student (Talib)')], default='student', max_length=20),
        ),
    ]
