# Generated by Django 5.2.11 on 2026-02-18 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user_alter_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='bank_details',
            field=models.TextField(blank=True, help_text='IBAN, Bank Name, or EasyPaisa/PayPal info'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed monthly pay', max_digits=10),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='salary_per_student',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Bonus pay per active student', max_digits=10),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Pay per hour (if applicable)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_data', to='accounts.profile'),
        ),
    ]
