# Generated by Django 5.2.11 on 2026-04-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacherprofile_bank_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Owner (Super Admin)'), ('head_manager', 'Head Manager'), ('manager', 'Manager'), ('teacher', 'Teacher (Ustad)'), ('student', 'Student (Talib)'), ('parent', 'Parent/Guardian')], default='student', max_length=20),
        ),
    ]
