# Generated by Django 5.2.11 on 2026-02-16 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_current_surah_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in USD or PKR', max_digits=10)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('month_paid_for', models.CharField(help_text='e.g. February 2026', max_length=50)),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('EasyPaisa', 'EasyPaisa'), ('PayPal', 'PayPal'), ('Other', 'Other')], default='Cash', max_length=50)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], default='Paid', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Optional Receipt ID', max_length=100, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student')),
            ],
        ),
    ]
