# Generated by Django 5.2.11 on 2026-04-03 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_user_assignment_studymaterial_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_account',
            field=models.ForeignKey(blank=True, help_text='The master parent account managing this student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
