# Generated by Django 5.2.11 on 2026-07-21 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_assignment_deleted_at_assignment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_whatsapp',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+[1-9]\\d{1,14}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+[1-9]\\d{1,14}$')]),
        ),
    ]
