# Generated by Django 5.2.11 on 2026-07-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION prevent_systemlog_modification()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'SystemLog records are immutable';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER prevent_systemlog_modification_trigger
            BEFORE UPDATE OR DELETE ON log_systemlog
            FOR EACH ROW EXECUTE FUNCTION prevent_systemlog_modification();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS prevent_systemlog_modification_trigger ON log_systemlog;
            DROP FUNCTION IF EXISTS prevent_systemlog_modification();
            """
        )
    ]
