# Generated by Django 5.2.11 on 2026-07-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_student'),
        ('students', '0007_assignment_deleted_at_assignment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('student', 'month_paid_for'), name='unique_payment_per_student_per_month'),
        ),
    ]
