# Generated by Django 5.2.11 on 2026-03-18 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Must match the LiveKit room name used in token grants.', max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivated rooms are hidden from the UI and reject new tokens.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_teacher', models.ForeignKey(blank=True, help_text='Teacher (Ustad) who hosts classes in this room.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livekit_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LiveKit Room',
                'verbose_name_plural': 'LiveKit Rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the teacher joined / started the class.')),
                ('ended_at', models.DateTimeField(blank=True, help_text='Timestamp when the session was closed. Null = still running.', null=True)),
                ('participant_count', models.PositiveIntegerField(default=0, help_text='Peak number of students who joined this session.')),
                ('notes', models.TextField(blank=True, help_text='Optional notes or topics covered during the session.')),
                ('host', models.ForeignKey(blank=True, help_text='The teacher who started this session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(help_text='The room this session took place in.', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='live_session.room')),
            ],
            options={
                'verbose_name': 'Session Log',
                'verbose_name_plural': 'Session Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
